### ISSUE TITLE
GKE upgrade v1.25 to v1.28 broke odigos daemonsets

### ISSUE THREAD

**Issue by dirtyren** [odigos-io/odigos#1321]
**Describe the bug**
GKE update from v1.25 pra v1.28 broke odigos daemonsets

I am getting the following error:
`Warning  FailedCreate  2m5s (x85 over 8h)  daemonset-controller  Error creating: insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical]}]
`
Another problem is that, after update, due to the daemonsets not starting, the apps orchestrated by Odigos also did not start.

**To Reproduce**
Update GKE from v1.25 to v1.28

**Comment by edeNFed** [comment]
Thanks for reporting @dirtyren I will fix it asap

**Comment by edeNFed** [comment]
@dirtyren I am working on a fix for GKE that should be released soon.
As a workaround you can run the following commands before installing Odigos and it will work:
`kubectl create namespace odigos-system`
`kubectl label namespace odigos-system odigos.io/system-object="true"`

Apply the following YAML:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: odigos-quota
  namespace: odigos-system
spec:
  hard:
    pods: "10k"
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
```
