### ISSUE TITLE
Missing / (slash) from https:// in destination images.

### ISSUE THREAD

**Issue by narfeta** [odigos-io/odigos#1501]
**Describe the bug**
Some image href links are not set correctly. In my case, when I use a VirtualService to access the service, the images are not rendering properly. As you can see in the screenshot, a `/` is missing from the `https://`

**To Reproduce**
1. Install odigos
2. Got to destinations
3. Click on Add a destination
3. Inspect html

**Expected behavior**
Render images from destinations

**Screenshots**
<img width="432" alt="imagem" src="https://github.com/user-attachments/assets/69816b93-13a8-4b4c-a49f-6e917ebbbc5e">
<img width="158" alt="imagem" src="https://github.com/user-attachments/assets/fb0a393f-111c-431a-b861-a648443c539f">
<img width="282" alt="imagem" src="https://github.com/user-attachments/assets/2de6a706-22e2-427e-8a68-d0a5113eb75b">
<img width="750" alt="imagem" src="https://github.com/user-attachments/assets/1044abae-b7e2-4623-bc53-ca59ab5884fd">
<img width="479" alt="imagem" src="https://github.com/user-attachments/assets/4490b969-862d-49cc-986b-40e6fe16c0cb">

**Comment by alonkeyval** [comment]
Thanks for bringing it to our attention, @narfeta. we will take a look.

**Comment by alonkeyval** [comment]
Hey @narfeta, can you share your VirtualService configuration yaml?

**Comment by narfeta** [comment]
sure, let me know if you need any other information. 

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: odigos-ui
  namespace: odigos-system
spec:
  gateways:
  - default/gtw-priv-https
  hosts:
  - odigos.mydomain.com
  http:
  - name: odigos-ui
    route:
    - destination:
        host: ui
        port:
          number: 3000
 ```
